make resizable again
On 2015-04-07, Termbox received a commit [1] that added `x` and `y` for mouse support, which causes an error in pytbclock when resizing the window:

    Traceback (most recent call last):
      File "./pytbclock.py", line 124, in <module>
        Clock().run()
      File "./pytbclock.py", line 112, in run
        event_type, ch, key, mod, w, h = event
    ValueError: too many values to unpack

The change should be working for old and current Termbox, and it doesn't have unused variables.

[1]: https://github.com/nsf/termbox/commit/71f40afac9bff4f27587270f561f8b2a7a32ca7c